---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: landing-b2-creds
  namespace: landing
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBAxSIrjrZcicJyXq8EWwrQhtDyoDxSOj6LHisPO1QMW/xgBEeVKWKe8yNrqMBDh9HuSlxM1Uy5RpzbcMKNUmfVSg2NtLQ0qjA4wNI3glhXs5hBfn4HyWbwVtQGDvERbtCrkxpyJH75sEUSYEhyWEAeI7gUY1n8/kfmWABGxMFZY8zDcofCWhA4YyWLDcf/h8swUI/dBQihD46VSyF6oNCvPRY8dA2xfE14mtXuwHENxX19iG8tXmytuC7UEvmL2iHfZehQDXQWTzDouoa6qbD9nEtpTcxdFWvqMJvkoKZCy7vQzl6cDvQACW40Dtj/wrZJRB5XVmcgwkXUXu7f5gLwSErLroxH+DjdC01N1V2/YPlbmV2XTkXwRjXpUGixv/ruzVabnFlb4QHo4UK1uDnDWDGJX8XinvrAp1+fboXWWs0Q9LkmH8b3ddz3hTMA7iBudo4rWvka3NOH+gOBtS0Bpp43oCQbFEi1iNKVzKUbBu1xequ/4vbuyaiMPTN0fDVy8830B1zzBxQEjdXPZWQyyzctF5mMjl0IHtOYlKY56fP2lotCOKxao4/1a5DtDzFyKqNDPWHhyfEgdCP+AF2z+zEEzIayTLSje43kryWRzf6aZ3h3I8uP02H/Op2U7GQWrhQlJdM//uEFFlsJ/Q0Y8+/C2OAHGmOzTvS+X8a8UgzjgBdtYo8zTWk56sB54ijl7O+i/0X/vrfw7jsPezQbJXCQQ/X+sKDj
    AWS_SECRET_ACCESS_KEY: AgATD3I3nikD/yUQxnLQdAeQqRAQGr1xCKcLpLq5QsDJfXzjK3vA/mu8YiZEcn9bYqhgGmUtjPnNmCAHKF0DMLd8a9ctfVoayjnadi1IZEOEp9e52jI8lfSn4bpVg5ijxzT2M1s7nqlpcVsxT63JF5cCPQFZ1ccySh+npI77XPLLjqq48l88FReOG5YQLCqVPKJa4bSIeFnQEEtuFYunrK0uUnCXqGcX/mqIsD0wD3Jx/e2Jw6cZMUgVChoZIjk58CcxE60Y2oHqUQuyAlQgJXVMufDP4uBbyphz6SpI+BKkyh6nXlYrRfJIHOBPLSy5DpRofByYZXO4xUBJ+EKKz1rbcDP5ek/WlLv8nrKmqXXFQ3KqXjB9nwjmbs2KOKkdenF2xmlkT5SR+q/z/UYQsMKRDWJWqpw+x1ewU24tvxOJ3EIOMfjkA2g2pIbAikvDSq25OcFOPxipxL6LZxm6iNGPdt900FrbnZGinHJvYUFIhPVIvY5q/oni+7b34zvEFfwfWymuEWxGERuv/LKF06cc9gK7zt5FZDe4VUMOOJDvJ/x+mgpQxL3PWGKQdlXa2eUnje/wdymfwtUB0hVDdY4F7sdyhyoKD6J6HxyVDbBRvxmoPfXch7AM/UVa5sTtftw4mQ2Z3Jb8IxP7vH6oahhtR6JXYbQ3WrZPawUP6DCiIOXy1QKnbfbLdqjJcUs5+26mzq1MOQ7C42FUbavY9/IwxyOfC63WbKM6QXGdIXJU
  template:
    metadata:
      name: landing-b2-creds
      namespace: landing
