---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secrets
  namespace: pocket-id
spec:
  encryptedData:
    encryption-key: AgApmF0ODZ8VOGt3OWZ3teioHTnnaaOz+F8NhxPy8XqV0vCTICYZV0mvmu8LrP7P7TRm9tUMR4x6Y9Il8mPhwH+kEJiqa3eXIDBhR2+6tXk5lbvuNYJBKrlsrn3Gpmkaj2SwTgzBQzpOIr7ntRC81br1CQKxtfFlonFiXSLw5Uk8qAhfHmNe6F+SjlD6wN0EDqXhAwZL+GqwCy8QGks+09WvfEialc23wHk9h5srqpJ5DOZjk0M6bxRAWhsWYcxDW2yML5UqebnS9/dPzLEbZ3yfZIsOOv5O+EOw7L3+k7+svzjV/xpoA9rZPdBJpdWl0JTyhFV97xfK/Mmb6swiue7eCtO+QtnMr+FLmxZAnH7GwtbsnyB5ldinmbQzlyrsj9qWl6R2jhi1C0U9BOtob4XFfGRSiZRC16tT7eNqdmLkRA2qKXt3wHOnGcsKGvqVLL+vasiSgjd6e1R6sw579Ds5OuqHUYTdwklL3ygYlpVTGoITfs3gaMEucrdtWmMqUYhMjoplUro1PYJ5s6/xPfQQnP3VZYpYl1NYRusjH320PToV1899fmDXerJbLnCS3X6N9NE4PpVUcvfCogIwJk12yuTBon7+K4Fj+snOzM4RUKppsO89EhKzFsVxqUMZBzsRg+YGyCScKUZZ6BvNuJ+UwdwzoxWyRN2+Ic70hShhtK2vrtCTD3P8IzCp+/GskhdjHNvSk5YM8rmvNVF7+FwQr1Kpcu4mD+w7lwlMMkxulcXwsa1svzAAkUNbKw==
  template:
    metadata:
      name: pocket-id-secrets
      namespace: pocket-id
